export enum ActionType {
  SEARCH_FETCH_START = "SEARCH_FETCH_START",
  SEARCH_FETCH_SUCCESS = "SEARCH_FETCH_SUCCESS",
  SEARCH_FETCH_FAILURE = "SEARCH_FETCH_FAILURE",

  ITEM_FETCH_START = "ITEM_FETCH_START",
  ITEM_FETCH_SUCCESS = "ITEM_FETCH_SUCCESS",
  ITEM_FETCH_FAILURE = "ITEM_FETCH_FAILURE",
}
